# Generated by Django 3.1.2 on 2020-10-28 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('points', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(auto_now=True)),
                ('is_discussion', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='artwork.artwork')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='artwork.comment')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='artwork.Tag'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
