# Generated by Django 3.1.2 on 2020-12-02 18:29

import artwork.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('points', models.FloatField(default=0)),
                ('creation_date', models.DateField(default=artwork.models.utc_now)),
                ('creation_time', models.TimeField(default=artwork.models.utc_now)),
                ('creation_date_time', models.DateTimeField(default=artwork.models.utc_now)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artwork.artworkmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('points', models.IntegerField(default=0)),
                ('creation_date', models.DateField(default=artwork.models.utc_now)),
                ('creation_time', models.TimeField(default=artwork.models.utc_now)),
                ('creation_date_time', models.DateTimeField(default=artwork.models.utc_now)),
                ('is_discussion', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='artwork.artworkmodel')),
            ],
        ),
    ]
