# Generated by Django 2.1.5 on 2020-11-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('points', models.FloatField(default=0)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(auto_now=True)),
                ('creation_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('points', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now=True)),
                ('creation_time', models.TimeField(auto_now=True)),
                ('is_discussion', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='artwork.ArtworkModel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artwork.ArtworkModel')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
