# Generated by Django 2.1.5 on 2020-12-08 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='artwork.CommentModel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='down_voters',
            field=models.ManyToManyField(blank=True, related_name='down_voted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='up_voters',
            field=models.ManyToManyField(blank=True, related_name='up_voted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='artwork.TagModel'),
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
