# Generated by Django 3.1.2 on 2020-11-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='creation_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
