# Generated by Django 3.1.2 on 2020-11-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='artwork.commentmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='artwork.TagModel'),
        ),
        migrations.AddField(
            model_name='artworkmodel',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
