# Generated by Django 3.1.2 on 2020-11-25 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20201124_2258'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_used_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_by_users', to='artwork.TagModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
